global_costmap:
  global_frame: map
  robot_base_frame: footprint
  transform_tolerance: 1.0
  update_frequency: 0.5
  resolution: 0.1
  static_map: true        # phải true để hiện map
  rolling_window: false   # false khi static_map: true
