<?xml version="1.0"?>
<package format="2">
  <name>navigate</name>
  <version>0.1.0</version>
  <description>Ohmni LiDAR mapping and navigation launch/config package.</description>

  <maintainer email="haeako@example.com">haeako</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>amcl</exec_depend>
  <exec_depend>gmapping</exec_depend>
  <exec_depend>map_server</exec_depend>
  <exec_depend>move_base</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>tf</exec_depend>

  <export/>
</package>
